<br /><br />
<div id="view-content" class="container">
    <div>
        <table class="table table-bordered">
            <tbody>
                <tr>                   
                     <td rowspan="2" class="col-lg-6"><button class="btn btn-primary china-row-btn pull-left">餐具类</button><img src="/qz/images/01.jpg" class="img-responsive pull-right"></td>
                     <td colspan="2" class="col-lg-6 text-center"><button class="btn btn-primary china-row-btn pull-left">功能类</button><img src="/qz/images/02.jpg" class="img-responsive pull-right"></td>
                </tr>
                <tr>                   
                    <td class="col-lg-3"><button class="btn btn-primary china-row-btn pull-left">摆设类</button><img src="/qz/images/03.jpg" class="img-responsive pull-right"></td>
                    <td class="col-lg-3"><button class="btn btn-primary china-row-btn pull-left">其他类</button></td>
                </tr>
            </tbody>
        </table>
    
    </div>
    <div class="row">
		<p class="col-lg-6 text-left">杯类：奶杯∣无把杯∣啤酒杯∣汤杯</p>
	    <p class="col-lg-6 text-right">更多∣More</p>
	</div>
    <table class="table table-bordered">
	   <tbody>
	       <tr>
	           <td class="col-lg-6">&nbsp;1<br><br><br><br><br></td>
	           <td class="col-lg-3">&nbsp;2</td>
	           <td class="col-lg-3">&nbsp;3</td>
	       </tr>
	   </tbody>
	</table>
	<div class="row">
		<p class="col-lg-6 text-left">盘类：平盘∣窝盘∣折边盘∣汤盘</p>
	    <p class="col-lg-6 text-right">更多∣More</p>
	</div>
</div>