

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/qz/images/favicon.png">

    <title>厦门七智进出口有限公司</title>

    <!-- Bootstrap core CSS -->
    <link href="/qz/jquery.plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/qz/css/carousel.css" rel="stylesheet">
    <link href="/qz/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">厦门七智进出口有限公司</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">厦门七智进出口有限公司</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">首页</a></li>
            <li><a href="#about">国贸</a></li>
            <li><a href="#contact">内贸</a></li>
            <li><a href="#contact">技术</a></li>
            <li><a href="/qz/about">合作</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">下拉菜单 <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="/qz/images/banner_01.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/qz/images/banner_02.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/qz/images/banner_03.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
      </div>
        <hr>
      <!-- Site footer -->
      <div class="footer">
        <div class="left text-left">
            <p>&copy; 厦门七智进出口有限公司 2014</p>
            <p>访问 七智陶瓷 在<a href="#">线商店</a>、<a href="#">实体店</a>，或查找在你附近的<a href="#">经销商</a>。</p>
        </div>
        <div class="right text-right">
            <p><a href="#" class="foot-link">网站地图</a>|<a href="热点新闻" class="foot-link">线商店</a>|<a href="#" class="foot-link">工作机会</a>|<a href="#" class="foot-link">联系我们</a></p>
            <p>闽公安网安备15009999号-1∣闽ICP备15008888号-1</p>
        </div>       
      </div>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/qz/jquery.plugins/jquery-1.11.1.min.js"></script>
    <script src="/qz/jquery.plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/qz/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>