<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/qz/images/favicon.png">

    <title>厦门七智进出口有限公司</title>

    <!-- Bootstrap core CSS -->
    <link href="/qz/jquery.plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/qz/css/carousel.css" rel="stylesheet">
    <link href="/qz/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
  <div class="wrap">
	<nav class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">厦门七智进出口有限公司</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">厦门七智进出口有限公司</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/qz">首页</a></li>
            <li><a href="/qz/about">我们</a></li>
            <li><a href="/qz/international">国际</a></li>
            <li class="active"><a href="/qz/domestic">国内</a></li>
<!--             <li><a href="/qz/technology">技术</a></li> -->
            <li><a href="/qz/cooperation">合作</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><img src="/qz/images/email.png" class="img-responsive"></a></li>
            <li><a href="#"><img src="/qz/images/weixin.png" class="img-responsive"></a></li>
            <li><a href="#"><img src="/qz/images/qq.png" class="img-responsive"></a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div> 
      <div class="container">
       <div class="navbar-header">
          <img src="/qz/images/logo.png" class="img-responsive">
        </div>
        <div class="navbar-inverse" id="drowdown">          
           <ul class="nav navbar-nav">
               <li><a href="/qz/domestic/mall">商超</a></li><li><a href="/qz/domestic/chain">连锁</a></li><li><a href="/qz/domestic/distribution">移动分销</a></li>
           </ul>
           <form class="navbar-form navbar-right" role="form">
              <span href="#">OA登录</span> |   
              <div class="form-group">
               <input type="text" placeholder="search" class="form-control">
                    </div>
                <span class="glyphicon glyphicon-search"></span>
            </form>
          </div>
     </div>     
    </nav>

    <?php echo $this->layout()->content;?>
    
     
     </div>
      <!-- Site footer -->
     <div id="footer" class="footer">
        <hr>
        <div class="container">
        <div class="left text-left">
            <p>&copy; 厦门七智进出口有限公司 2014</p>
            <p>访问 七智陶瓷 在<a href="#">线商店</a>、<a href="#">实体店</a>，或查找在你附近的<a href="#">经销商</a>。</p>
        </div>
        <div class="right text-right">
            <p><a href="#" class="foot-link">网站地图</a>|<a href="#" class="foot-link">线商店</a>|<a href="#" class="foot-link">工作机会</a>|<a href="#" class="foot-link">联系我们</a></p>
            <p>闽公安网安备15009999号-1∣闽ICP备15008888号-1</p>
        </div>       
      </div>
     </div>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/qz/jquery.plugins/jquery-1.11.1.min.js"></script>
    <script src="/qz/jquery.plugins/bootstrap/js/bootstrap.min.js"></script>
     <script src="/qz/js/nav.js"></script>
    <script src="/qz/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>