    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="/qz/images/banner_01.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/qz/images/banner_02.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/qz/images/banner_03.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
        <div class="col-lg-4">
         <div class="item">
            <h3>中国陶瓷行业分析</h3>
            <div class="row brief">            
                <p class="col-lg-8">厦门市七智进出口有限公司是日用陶瓷等产品专业生产加工的公司，拥有完整、科学的质量管理体系。厦门市七智进出口有限公司的诚信、实力和产品质量获得业界的认可。欢迎各界朋友莅临参观、指导和业务洽谈。</p>
                <img src="/qz/images/pic1.png" class="col-lg-4 img-responsive">
           </div>          
           <p><a class="btn btn-success" href="#" role="button">详细 &raquo;</a></p>
         </div>
        </div>
      </div>
</div>
      