
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/qz/images/favicon.png">

    <title>厦门七智进出口有限公司</title>

    <!-- Bootstrap core CSS -->
    <link href="/qz/jquery.plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/qz/css/justified-nav.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">厦门七智进出口有限公司</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/qz">首页</a></li>
            <li><a href="/qz/international">国贸</a></li>
            <li><a href="/qz/domestic">内贸</a></li>
            <li><a href="/qz/technology">技术</a></li>
            <li><a href="/qz/about">合作</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><img src="/qz/images/email.png" class="img-responsive"></a></li>
            <li><a href="#"><img src="/qz/images/weixin.png" class="img-responsive"></a></li>
            <li><a href="#"><img src="/qz/images/qq.png" class="img-responsive"></a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <!-- Jumbotron -->
      <div class="jumbotron text-left" style="background-color:#fff">
        <?php echo $this->ErrorCode; echo $this->ErrorMessage;?>
        <p><a href="/qz" class="btn btn-primary btn-lg" role="button">首页</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
      </div>


    </div> <!-- /container -->

    <script src="/qz/jquery.plugins/jquery-1.11.1.min.js"></script>
    <script src="/qz/jquery.plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/qz/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

